### ISSUE TITLE
It was me. Though, Errno2 re: config.yaml is thrown

### ISSUE THREAD

**Issue by iamrhyot** [NathanDuma/LinkedIn-Easy-Apply-Bot#21]
Hey there @NathanDuma, thanks in advance for expanding upon this and go Team Canada. 

As hinted in the title, I have a feeling this is somehow my own error, but when attempting to run the script in cmd, as soon as I press enter, I'm returned with another C:\ and nothing happens. Forgive me, I really don't have much experience with command line stuff. 

I found your fork after attempting to launch the original, yet was getting an error wherein the script would initialize, chrome would open but then the config.yaml file wasn't being found by linkedineasyapply.py. So, scrapped that, set up the config for yours (which looks great btw) and so far, dude.

Thanks in advance!

**Comment by iamrhyot** [comment]
... it was me
though i'm running into the following:

`Traceback (most recent call last):
  File "C:\Users\gja22\Desktop\LinkedIn-Easy-Apply-Bot-master\main.py", line 122, in <module>
    parameters = validate_yaml()
  File "C:\Users\gja22\Desktop\LinkedIn-Easy-Apply-Bot-master\main.py", line 25, in validate_yaml
    with open("config.yaml", 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'`

The file config.yaml is in the same folder as the main.py script as well, and hasn't been renamed or had the extension changed in any way.

**Comment by iamrhyot** [comment]
Solved with a CD. Just made a shortcut to cmd.exe with the CD and initialization commands written in to make a clickable launch.
