### ISSUE TITLE
Anytime I try to start the bot I get this error.

### ISSUE THREAD

**Issue by BrandonMilam** [NathanDuma/LinkedIn-Easy-Apply-Bot#23]
`bmilam@Snow:/mnt/c/Users/betak/downloads/LinkedIn-Easy-Apply-Bot-master$ python3 linkedineasyapply.py
Traceback (most recent call last):
  File "linkedineasyapply.py", line 1, in <module>
    import time, random, csv, pyautogui, pdb, traceback, sys
  File "/home/bmilam/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/bmilam/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'`

**Comment by SantaHub** [comment]
You must be running on a server without display installed.  Trye : sudo apt install ubuntu-desktop

**Comment by cbroker1** [comment]
@SantaHub hijacking this issue thread to ask you another, unrelated, question. My bot is running fine until it gets to the end of the first page. It then just hangs, no activity or error. Any ideas?

**Comment by NathanDuma** [comment]
How long does it hang? There is a minimum of 15 minutes before going to the
next page, and the timer starts as soon as the page is loaded.
