### ISSUE TITLE
Error   assert len(parameters['uploads']) >= 1 and 'resume' in parameters['uploads']

### ISSUE THREAD

**Issue by soychristophe** [NathanDuma/LinkedIn-Easy-Apply-Bot#38]
I have the following error and I don't know how to solve it, any idea, thank you very much for this great script.

I have configured the config.yaml in this way and the file is found.
```
uploads:
resume: C:\LinkedInBot\cv.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf
```
and gives the following error
```
Traceback (most recent call last):
  File "C:\LinkedInBot\main.py", line 122, in <module>
    parameters = validate_yaml()
  File "C:\LinkedInBot\main.py", line 76, in validate_yaml
    assert len(parameters['uploads']) >= 1 and 'resume' in parameters['uploads']
TypeError: object of type 'NoneType' has no len()
```

**Comment by soychristophe** [comment]
Solved...

It seems that it was not tabbed correctly in config.yaml.
