### ISSUE TITLE
Cant find 'job-card-list__title' although it exists

### ISSUE THREAD

**Issue by mniebieski** [NathanDuma/LinkedIn-Easy-Apply-Bot#5]
Hey, I've tried using your app, however get following issue:

Traceback (most recent call last):
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\linkedineasyapply.py", line 167, in apply_jobs
    job_el = job_tile.find_element_by_class_name('job-card-list__title')
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 398, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Komputer\PycharmProjects\CVAutomation_1\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.77)
  
  I'm not sure why it pops up :-/ It seems to be looking for class name 'job-card-list__title', but then returns error that cant find element. I checked that the element with such class name does exist.
  
  Any thoughts?

**Comment by NathanDuma** [comment]
Do you know if the job list page was refreshed or changed at all? The only way I could think that this could happen is that the reference to the job tile is no longer on the page. I guess one other way could be linkedin changing the job elements on the fly (maybe they are performing A/B testing?) but I haven't seen this happen.
Please watch the bot apply to some jobs and tell me where it is failing. I'm curious to know.
